Update CrDroid.yml

diff --git a/.github/workflows/CrDroid.yml b/.github/workflows/CrDroid.yml
--- a/.github/workflows/CrDroid.yml
+++ b/.github/workflows/CrDroid.yml
@@ -106,23 +106,22 @@ jobs:
 
     - name: Run crave devspace
       run: |
-        crave ${{ secrets.CRAVE_FLAGS }} devspace -- "echo "Looking for runner..."
-          # Look for whether there's a runner folder set up
-          if [ -f actions-runner/run.sh ] ; then
-            echo "Runner found! Restarting it..."
-          else
-            echo "Error! Runner not found!"
-            exit 1
-          fi
-
-        if tmux has-session -t ghactions; then 
-          echo "Runner is already Running" 
-        else 
-          tmux kill-session -t ghactions;
-          tmux new-session -d -s ghactions 
-          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
-          echo "Runner Started"
-        fi "
+        crave ${{ secrets.CRAVE_FLAGS }} devspace -- "\
+          echo \"Looking for runner...\" && \
+          if [ -f actions-runner/run.sh ] ; then \
+            echo \"Runner found! Restarting it...\"; \
+          else \
+            echo \"Error! Runner not found!\"; \
+            exit 1; \
+          fi && \
+          if tmux has-session -t ghactions; then \
+            echo \"Runner is already Running\"; \
+          else \
+            tmux kill-session -t ghactions; \
+            tmux new-session -d -s ghactions; \
+            tmux send-keys -t ghactions './actions-runner/run.sh' Enter; \
+            echo \"Runner Started\"; \
+          fi"
   prepare:
     name: Prepare for Building
     runs-on: ubuntu-latest
@@ -493,46 +492,46 @@ jobs:
         echo "Check foss.crave.io Dashboard to see builds"
         echo "Running build's log will show up here!"
 
-
-        crave ${{ secrets.CRAVE_FLAGS }} run --no-patch ${PAID} ${CLEAN} -- "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
-        # Clone local_manifests repository
-        $BUILD_DIFFERENT_ROM ; \
-        $LOCAL_MANIFEST && \
-
-        # Sync the repositories
-        if [ -f /usr/bin/resync ]; then
-          /usr/bin/resync # For compatibility with Omansh's Docker image 
-        else
-          /opt/crave/resync.sh
-        fi && \
-
-       (cd system/core && \
-       git remote add crdroid https://github.com/crdroidandroid/android_system_core && \
-       git config pull.rebase true && \
-       git pull crdroid 13.0) && \
-       
-       (cd frameworks/base && \
-       git remote add crdroid https://github.com/crdroidandroid/android_frameworks_base && \
-       git config pull.rebase true && \
-       git pull crdroid 13.0) && \
-       
-       (cd frameworks/native && \
-       git remote add crdroid https://github.com/crdroidandroid/android_frameworks_native && \
-       git config pull.rebase true && \
-       git pull crdroid 13.0) && \
-
-        # Set up build environment
-        export BUILD_USERNAME=${{ github.actor }} ; \
-        export BUILD_HOSTNAME=crave ; \
-        source build/envsetup.sh && \
-
-        echo \"Repository: ${{ github.repository }}\" && \
-        echo \"Run ID: ${{ github.run_id }}\" && \
-
-        # Build the ROM
-        $LUNCH && \
-        make installclean && \
-        ${{ github.event.inputs.BUILD_COMMAND }}"
+        crave ${{ secrets.CRAVE_FLAGS }} run --no-patch ${PAID} ${CLEAN} -- "\
+          rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
+          # Clone local_manifests repository
+          $BUILD_DIFFERENT_ROM ; \
+          $LOCAL_MANIFEST && \
+          
+          # Sync the repositories
+          if [ -f /usr/bin/resync ]; then
+            /usr/bin/resync
+          else
+            /opt/crave/resync.sh
+          fi && \
+          
+          (cd system/core && \
+          git remote add crdroid https://github.com/crdroidandroid/android_system_core && \
+          git config pull.rebase true && \
+          git pull crdroid 13.0) && \
+          
+          (cd frameworks/base && \
+          git remote add crdroid https://github.com/crdroidandroid/android_frameworks_base && \
+          git config pull.rebase true && \
+          git pull crdroid 13.0) && \
+          
+          (cd frameworks/native && \
+          git remote add crdroid https://github.com/crdroidandroid/android_frameworks_native && \
+          git config pull.rebase true && \
+          git pull crdroid 13.0) && \
+          
+          # Set up build environment
+          export BUILD_USERNAME=${{ github.actor }} && \
+          export BUILD_HOSTNAME=crave && \
+          source build/envsetup.sh && \
+          
+          echo \"Repository: ${{ github.repository }}\" && \
+          echo \"Run ID: ${{ github.run_id }}\" && \
+          
+          # Build the ROM
+          $LUNCH && \
+          make installclean && \
+          ${{ github.event.inputs.BUILD_COMMAND }}"
       timeout-minutes: 1440
 
       # Send Build 'status' notification (Success)
